"use client";
import { useState } from "react";
import type { Announcement } from "@/lib/database.types";
import { ActionForm } from "@/components/action-form";
import { deleteAnnouncement,saveAnnouncement } from "@/app/(app)/dashboard/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
const field="block w-full rounded-md border bg-background p-2";
export function AnnouncementsPanel({announcements,teacher,userId}:{announcements:Announcement[];teacher:boolean;userId:string}){
 const [editing,setEditing]=useState<Announcement|null|undefined>(undefined);
 return <section className="mt-6 space-y-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-medium">Announcements</h2><p className="mt-1 text-sm text-muted-foreground">Studio-wide updates and reminders.</p></div>{teacher&&<Button onClick={()=>setEditing(null)}>Post announcement</Button>}</div>
 {editing!==undefined&&<div className="rounded-xl border bg-card p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-medium">{editing?"Edit announcement":"New announcement"}</h3><Button variant="ghost" onClick={()=>setEditing(undefined)}>Close</Button></div><ActionForm action={saveAnnouncement} label={editing?"Save changes":"Publish announcement"}><input type="hidden" name="id" value={editing?.id??""}/><label className="block text-sm">Title<Input name="title" maxLength={120} required defaultValue={editing?.title}/></label><label className="block text-sm">Message<textarea className={`${field} min-h-28`} name="body" maxLength={4000} required defaultValue={editing?.body}/></label><label className="block text-sm">Show through <span className="text-muted-foreground">(optional)</span><Input type="date" name="expires_at" defaultValue={editing?.expires_at?.slice(0,10)??""}/></label></ActionForm>{editing&&<details className="mt-5"><summary className="cursor-pointer text-sm text-destructive">Delete announcement</summary><p className="my-3 text-sm">This removes the announcement for everyone.</p><ActionForm action={deleteAnnouncement} label="Confirm deletion"><input type="hidden" name="id" value={editing.id}/></ActionForm></details>}</div>}
 <div className="space-y-3">{announcements.length===0&&<p className="rounded-xl border bg-card p-6 text-sm text-muted-foreground">No announcements have been posted.</p>}{announcements.map(a=><article key={a.id} className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{a.title}</h3><p className="mt-1 text-xs text-muted-foreground">Posted {new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(a.published_at))}{a.expires_at&&` · Through ${new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(a.expires_at))}`}</p></div>{teacher&&a.author_id===userId&&<Button variant="outline" onClick={()=>setEditing(a)}>Edit</Button>}</div><p className="mt-3 whitespace-pre-wrap text-sm">{a.body}</p></article>)}</div></section>;
}
