"use client";
import { useState } from "react";
import type { Assignment } from "@/lib/database.types";
import { ActionForm } from "@/components/action-form";
import { deleteAssignment,saveAssignment } from "@/app/(app)/assignments/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
const field="block w-full rounded-md border bg-background p-2";
type Person={id:string;full_name:string;membershipRole:string};
export function AssignmentsWorkspace({assignments,people,teacher,userId}:{assignments:Assignment[];people:Person[];teacher:boolean;userId:string}){
 const [editing,setEditing]=useState<Assignment|null|undefined>(undefined),[filter,setFilter]=useState<"active"|"archived">("active");
 const visible=assignments.filter(a=>a.status===filter),person=(id:string|null)=>id?people.find(p=>p.id===id)?.full_name??"Student":"Whole studio";
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg border bg-card p-1"><button className={`rounded-md px-3 py-2 text-sm ${filter==="active"?"bg-primary text-primary-foreground":"text-muted-foreground"}`} onClick={()=>setFilter("active")}>Current</button>{teacher&&<button className={`rounded-md px-3 py-2 text-sm ${filter==="archived"?"bg-primary text-primary-foreground":"text-muted-foreground"}`} onClick={()=>setFilter("archived")}>Archived</button>}</div>{teacher&&<Button onClick={()=>setEditing(null)}>Create assignment</Button>}</div>
 <section className="grid gap-4 md:grid-cols-2">{visible.length===0&&<p className="rounded-xl border p-8 text-muted-foreground md:col-span-2">{filter==="active"?"No current assignments.":"No archived assignments."}</p>}{visible.map(a=>{const overdue=a.due_date&&a.status==="active"&&a.due_date<new Date().toISOString().slice(0,10);return <article key={a.id} className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-muted px-2 py-1 text-xs font-medium">{person(a.student_id)}</span><h2 className="mt-3 font-semibold">{a.title}</h2></div>{teacher&&a.teacher_id===userId&&<Button variant="outline" onClick={()=>setEditing(a)}>Edit</Button>}</div>{a.instructions&&<p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{a.instructions}</p>}<p className={`mt-4 text-xs ${overdue?"font-medium text-destructive":"text-muted-foreground"}`}>{a.due_date?`${overdue?"Overdue · ":"Due "}${new Date(`${a.due_date}T12:00:00`).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}`:"No due date"}</p></article>;})}</section>
 {editing!==undefined&&<section className="rounded-xl border bg-card p-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">{editing?"Edit assignment":"New assignment"}</h2><Button variant="ghost" onClick={()=>setEditing(undefined)}>Close</Button></div><AssignmentEditor key={editing?.id??"new"} assignment={editing} people={people}/>{editing&&<details className="mt-5"><summary className="cursor-pointer text-sm text-destructive">Delete assignment</summary><p className="my-3 text-sm">This permanently removes the assignment.</p><ActionForm action={deleteAssignment} label="Confirm deletion"><input type="hidden" name="id" value={editing.id}/></ActionForm></details>}</section>}
 </div>;
}
function AssignmentEditor({assignment,people}:{assignment:Assignment|null;people:Person[]}){
 const [target,setTarget]=useState(assignment?.student_id?"student":"studio");
 return <ActionForm action={saveAssignment} label="Save assignment"><input type="hidden" name="id" value={assignment?.id??""}/><label className="block text-sm">Assign to<select className={field} name="target" value={target} onChange={e=>setTarget(e.target.value)}><option value="studio">Whole studio</option><option value="student">One student</option></select></label>{target==="student"&&<label className="block text-sm">Student<select className={field} name="student_id" required defaultValue={assignment?.student_id??""}><option value="">Choose a student</option>{people.filter(p=>p.membershipRole==="student").map(p=><option value={p.id} key={p.id}>{p.full_name}</option>)}</select></label>}<label className="block text-sm">Title<Input name="title" required maxLength={120} defaultValue={assignment?.title}/></label><label className="block text-sm">Instructions<textarea className={`${field} min-h-32`} name="instructions" maxLength={6000} defaultValue={assignment?.instructions} placeholder="Practice goals, repertoire, tempo, or preparation notes"/></label><label className="block text-sm">Due date<Input type="date" name="due_date" defaultValue={assignment?.due_date??""}/></label>{assignment&&<label className="block text-sm">Status<select className={field} name="status" defaultValue={assignment.status}><option value="active">Current</option><option value="archived">Archived</option></select></label>}</ActionForm>;
}
