"use client";
import Link from "next/link";
import { useState,useEffect } from "react";
import type { AvailabilityRule,BookingRequest,CalendarEvent } from "@/lib/database.types";
import { ActionForm } from "@/components/action-form";
import { addAvailability,cancelRequest,deleteEvent,removeAvailability,requestLesson,respondRequest,saveEvent } from "@/app/(app)/calendar/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
const field="block w-full rounded-md border bg-background p-2";
const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const eventNames={lesson:"Lesson",studio_event:"Studio event",unavailable:"Unavailable"};
function localValue(iso:string){const d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}T${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;}
function clock(minutes:number){const h=Math.floor(minutes/60),m=minutes%60;return new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(2020,0,1,h,m));}
type Person={id:string;full_name:string;membershipRole:string};
export function CalendarView({events,availability,requests,teacher,userId,month,people}:{events:CalendarEvent[];availability:AvailabilityRule[];requests:BookingRequest[];teacher:boolean;userId:string;month:string;people:Person[]}){
 const [zone,setZone]=useState("UTC"),[view,setView]=useState<"calendar"|"availability"|"requests">("calendar");useEffect(()=>setZone(Intl.DateTimeFormat().resolvedOptions().timeZone),[]);
 const format=(iso:string)=>new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:zone}).format(new Date(iso));
 const person=(id:string)=>people.find(p=>p.id===id)?.full_name??"Studio member";
 return <div className="space-y-5">
  <nav className="flex gap-1 rounded-xl border bg-card p-1" aria-label="Scheduling views">{(["calendar","availability","requests"] as const).map(tab=><button key={tab} onClick={()=>setView(tab)} className={`flex-1 rounded-lg px-3 py-2 text-sm font-medium capitalize ${view===tab?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-muted"}`}>{tab}{tab==="requests"&&requests.filter(r=>r.status==="pending").length>0&&` (${requests.filter(r=>r.status==="pending").length})`}</button>)}</nav>
  {view==="calendar"&&<CalendarPanel events={events} teacher={teacher} userId={userId} month={month} people={people} zone={zone} format={format}/>} 
  {view==="availability"&&<AvailabilityPanel rules={availability} teacher={teacher} zone={zone}/>} 
  {view==="requests"&&<RequestsPanel rules={availability} requests={requests} teacher={teacher} zone={zone} format={format} person={person}/>} 
 </div>;
}
function CalendarPanel({events,teacher,userId,month,people,zone,format}:{events:CalendarEvent[];teacher:boolean;userId:string;month:string;people:Person[];zone:string;format:(iso:string)=>string}){
 const [editing,setEditing]=useState<CalendarEvent|null|undefined>(undefined),[day,setDay]=useState<string|null>(null);
 const dateKey=(iso:string)=>{const parts=new Intl.DateTimeFormat("en-US",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:zone}).formatToParts(new Date(iso));return ["year","month","day"].map(t=>parts.find(p=>p.type===t)?.value).join("-");};
 const base=new Date(`${month}-01T12:00:00Z`),daysInMonth=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+1,0)).getUTCDate();function adjacent(n:number){const d=new Date(base);d.setUTCMonth(d.getUTCMonth()+n);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`;}
 const inMonth=events.filter(e=>dateKey(e.starts_at).startsWith(month)),visible=day?inMonth.filter(e=>dateKey(e.starts_at)===day):inMonth;
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href={`/calendar?month=${adjacent(-1)}`} aria-label="Previous month">←</Link><h2 className="font-semibold">{base.toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</h2><Link href={`/calendar?month=${adjacent(1)}`} aria-label="Next month">→</Link></div>{teacher&&<Button onClick={()=>setEditing(null)}>Schedule</Button>}</div>
 <p className="text-xs text-muted-foreground">Times shown in {zone}. Select a date to filter the agenda.</p>
 <div className="grid grid-cols-7 overflow-hidden rounded-xl border bg-card">{days.map(d=><div className="p-2 text-center text-xs text-muted-foreground" key={d}>{d.slice(0,3)}</div>)}{Array.from({length:base.getUTCDay()},(_,i)=><div key={`blank-${i}`}/>)}{Array.from({length:daysInMonth},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`,count=inMonth.filter(e=>dateKey(e.starts_at)===date).length;return <button key={date} aria-pressed={day===date} aria-label={`${date}, ${count} events`} className={`min-h-16 border-t p-2 text-center text-sm sm:min-h-20 ${day===date?"bg-accent":"hover:bg-muted"}`} onClick={()=>setDay(day===date?null:date)}>{i+1}{count>0&&<span className="mx-auto mt-1 block h-1.5 w-1.5 rounded-full bg-primary"/>}</button>;})}</div>
 {day&&<Button variant="ghost" onClick={()=>setDay(null)}>Show whole month</Button>}
 <section className="space-y-3" aria-label="Event agenda">{visible.length===0&&<p className="rounded-xl border p-6 text-muted-foreground">No events scheduled {day?"on this day":"this month"}.</p>}{visible.map(e=><article className="rounded-xl border bg-card p-5" key={e.id}><div className="flex flex-wrap justify-between gap-3"><div><span className="rounded-full bg-muted px-2 py-1 text-xs font-medium">{eventNames[e.event_type]}</span><h3 className="mt-3 font-semibold">{e.title}</h3><p className="mt-1 text-sm">{format(e.starts_at)} – {format(e.ends_at)}</p><p className="mt-1 text-sm text-muted-foreground">{e.student_id?people.find(p=>p.id===e.student_id)?.full_name??"Student":e.event_type==="studio_event"?"Whole studio":"Teacher calendar"}{e.location&&` · ${e.location}`}</p>{e.description&&<p className="mt-2 whitespace-pre-wrap text-sm">{e.description}</p>}{e.recurrence_group_id&&<p className="mt-2 text-xs text-muted-foreground">Part of a weekly series</p>}</div>{teacher&&e.teacher_id===userId&&<Button variant="outline" onClick={()=>setEditing(e)}>Edit</Button>}</div></article>)}</section>
 {editing!==undefined&&<section className="rounded-xl border bg-card p-6" aria-label="Event editor"><div className="mb-4 flex justify-between"><h2 className="font-semibold">{editing?"Edit event":"Add to schedule"}</h2><Button variant="ghost" onClick={()=>setEditing(undefined)}>Close</Button></div><EventEditor key={editing?.id??"new"} event={editing} people={people}/>{editing&&<details className="mt-5"><summary className="cursor-pointer text-sm text-destructive">Delete event</summary><p className="my-3 text-sm">This removes this event from everyone’s calendar.</p><ActionForm action={deleteEvent} label="Confirm deletion"><input type="hidden" name="id" value={editing.id}/></ActionForm></details>}</section>}
 </div>;
}
function EventEditor({event,people}:{event:CalendarEvent|null;people:Person[]}){
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone,[kind,setKind]=useState(event?.event_type??"lesson");
 async function submit(_:import("@/components/action-form").ActionResult,form:FormData){const start=String(form.get("starts_local")??""),end=String(form.get("ends_local")??"");if(!Number.isFinite(Date.parse(start))||!Number.isFinite(Date.parse(end)))return {error:"Enter a valid start and end time."};if(localValue(new Date(start).toISOString())!==start||localValue(new Date(end).toISOString())!==end)return {error:"This time does not exist due to a daylight-saving change. Choose another time."};form.set("starts_at",new Date(start).toISOString());form.set("ends_at",new Date(end).toISOString());form.set("time_zone",zone);return saveEvent({},form);}
 return <ActionForm action={submit} label="Save schedule"><input type="hidden" name="id" value={event?.id??""}/><label className="block text-sm">Type<select className={field} name="event_type" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="lesson">Lesson</option><option value="studio_event">Studio event</option><option value="unavailable">Unavailable</option></select></label><label className="block text-sm">Title<Input name="title" required maxLength={120} defaultValue={event?.title??(kind==="lesson"?"Lesson":kind==="studio_event"?"Studio event":"Unavailable")}/></label>{kind==="lesson"&&<label className="block text-sm">Student<select className={field} name="student_id" required defaultValue={event?.student_id??""}><option value="">Choose a student</option>{people.filter(p=>p.membershipRole==="student").map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Starts<Input type="datetime-local" required name="starts_local" defaultValue={event?localValue(event.starts_at):""}/></label><label className="text-sm">Ends<Input type="datetime-local" required name="ends_local" defaultValue={event?localValue(event.ends_at):""}/></label></div><p className="text-xs text-muted-foreground">Time zone: {zone}. Everyone sees this in their own time zone.</p>{!event&&<label className="block text-sm">Repeat<select className={field} name="repeat_count" defaultValue="1"><option value="1">Does not repeat</option><option value="4">Weekly for 4 weeks</option><option value="8">Weekly for 8 weeks</option><option value="12">Weekly for 12 weeks</option><option value="16">Weekly for 16 weeks</option><option value="24">Weekly for 24 weeks</option></select></label>}<label className="block text-sm">Location<Input name="location" maxLength={300} defaultValue={event?.location}/></label><label className="block text-sm">Notes<textarea className={field} name="description" maxLength={4000} defaultValue={event?.description}/></label></ActionForm>;
}
function AvailabilityPanel({rules,teacher,zone}:{rules:AvailabilityRule[];teacher:boolean;zone:string}){
 return <section className="space-y-4"><div><h2 className="font-semibold">Weekly availability</h2><p className="mt-1 text-sm text-muted-foreground">{teacher?"Set the windows students can use when requesting lessons.":"These are the times your teacher accepts lesson requests."}</p></div><div className="grid gap-3 sm:grid-cols-2">{rules.length===0&&<p className="rounded-xl border p-6 text-muted-foreground sm:col-span-2">No availability has been shared yet.</p>}{rules.map(r=><article key={r.id} className="rounded-xl border bg-card p-4"><p className="font-medium">{days[r.weekday]}</p><p className="text-sm text-muted-foreground">{clock(r.start_minute)} – {clock(r.end_minute)}</p><p className="mt-1 text-xs text-muted-foreground">{r.time_zone}</p>{teacher&&<ActionForm className="mt-3" action={removeAvailability} label="Remove"><input type="hidden" name="id" value={r.id}/></ActionForm>}</article>)}</div>{teacher&&<div className="rounded-xl border bg-card p-5"><h3 className="mb-4 font-medium">Add an availability window</h3><ActionForm action={addAvailability} label="Add availability"><input type="hidden" name="time_zone" value={zone}/><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm">Day<select className={field} name="weekday">{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label className="text-sm">From<Input type="time" name="start_time" required defaultValue="15:00"/></label><label className="text-sm">Until<Input type="time" name="end_time" required defaultValue="18:00"/></label></div><p className="text-xs text-muted-foreground">Saved in {zone}.</p></ActionForm></div>}</section>;
}
function RequestsPanel({rules,requests,teacher,zone,format,person}:{rules:AvailabilityRule[];requests:BookingRequest[];teacher:boolean;zone:string;format:(iso:string)=>string;person:(id:string)=>string}){
 const teachers=Array.from(new Map(rules.map(r=>[r.teacher_id,r])).keys());
 async function submit(_:import("@/components/action-form").ActionResult,form:FormData){const start=String(form.get("starts_local")??""),duration=Number(form.get("duration")??60);if(!Number.isFinite(Date.parse(start)))return {error:"Choose a valid lesson time."};const date=new Date(start);form.set("starts_at",date.toISOString());form.set("ends_at",new Date(date.getTime()+duration*60000).toISOString());form.set("time_zone",zone);return requestLesson({},form);}
 return <section className="space-y-4"><div><h2 className="font-semibold">Lesson requests</h2><p className="mt-1 text-sm text-muted-foreground">{teacher?"Approve a request to place it on the calendar automatically.":"Ask for a lesson inside one of the weekly availability windows."}</p></div>{!teacher&&<div className="rounded-xl border bg-card p-5"><h3 className="mb-4 font-medium">Request a lesson</h3>{teachers.length===0?<p className="text-sm text-muted-foreground">Your teacher needs to share availability before you can request a time.</p>:<ActionForm action={submit} label="Send request"><label className="block text-sm">Teacher<select className={field} name="teacher_id">{teachers.map(id=><option key={id} value={id}>{person(id)}</option>)}</select></label><label className="block text-sm">Start time<Input type="datetime-local" name="starts_local" required/></label><label className="block text-sm">Length<select className={field} name="duration" defaultValue="60"><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label><p className="text-xs text-muted-foreground">Times entered in {zone}.</p><label className="block text-sm">Note<textarea className={field} name="note" maxLength={1000} placeholder="Anything your teacher should know?"/></label></ActionForm>}</div>}
 <div className="space-y-3">{requests.length===0&&<p className="rounded-xl border p-6 text-muted-foreground">No lesson requests yet.</p>}{requests.map(r=><article key={r.id} className="rounded-xl border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-xs font-medium ${r.status==="approved"?"bg-green-100 text-green-800":r.status==="pending"?"bg-amber-100 text-amber-800":"bg-muted"}`}>{r.status}</span><h3 className="mt-3 font-semibold">{teacher?person(r.student_id):person(r.teacher_id)}</h3><p className="mt-1 text-sm">{format(r.requested_start)} – {format(r.requested_end)}</p>{r.note&&<p className="mt-2 text-sm">{r.note}</p>}{r.response_note&&<p className="mt-2 text-sm text-muted-foreground">Teacher response: {r.response_note}</p>}</div></div>{r.status==="pending"&&(teacher?<div className="mt-4 grid gap-3 sm:grid-cols-2"><ActionForm action={respondRequest} label="Approve"><input type="hidden" name="id" value={r.id}/><input type="hidden" name="decision" value="approved"/></ActionForm><ActionForm action={respondRequest} label="Decline"><input type="hidden" name="id" value={r.id}/><input type="hidden" name="decision" value="declined"/></ActionForm></div>:<ActionForm className="mt-4" action={cancelRequest} label="Cancel request"><input type="hidden" name="id" value={r.id}/></ActionForm>)}</article>)}</div></section>;
}
