"use client";
import Link from "next/link";
import { useState,useEffect } from "react";
import type { CalendarEvent } from "@/lib/database.types";
import { ActionForm } from "@/components/action-form";
import { saveEvent,deleteEvent } from "@/app/(app)/calendar/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
const field="block w-full rounded-md border bg-background p-2";
function localValue(iso:string){const d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}T${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;}
export function CalendarView({events,teacher,userId,month,people}:{events:CalendarEvent[];teacher:boolean;userId:string;month:string;people:{id:string;full_name:string;membershipRole:string}[]}){
 const [zone,setZone]=useState("UTC");useEffect(()=>setZone(Intl.DateTimeFormat().resolvedOptions().timeZone),[]);
 const format=(iso:string)=>new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:zone}).format(new Date(iso));
 const dateKey=(iso:string)=>{const parts=new Intl.DateTimeFormat("en-US",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:zone}).formatToParts(new Date(iso));return ["year","month","day"].map(t=>parts.find(p=>p.type===t)?.value).join("-");};
 const [editing,setEditing]=useState<CalendarEvent|null|undefined>(undefined),[day,setDay]=useState<string|null>(null);
 const base=new Date(`${month}-01T12:00:00Z`),days=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();
 function adjacent(n:number){const d=new Date(base);d.setMonth(d.getMonth()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;}
 const inMonth=events.filter(e=>dateKey(e.starts_at).startsWith(month));
 const visible=day?inMonth.filter(e=>dateKey(e.starts_at)===day):inMonth;
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href={`/calendar?month=${adjacent(-1)}`} aria-label="Previous month">←</Link><h2 className="font-semibold">{base.toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</h2><Link href={`/calendar?month=${adjacent(1)}`} aria-label="Next month">→</Link></div>{teacher&&<Button onClick={()=>setEditing(null)}>Schedule event</Button>}</div>
 <p className="text-xs text-muted-foreground">Times shown in {zone}. Select a date to filter the agenda.</p>
 <div className="grid grid-cols-7 overflow-hidden rounded-xl border bg-card">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div className="p-2 text-center text-xs text-muted-foreground" key={d}>{d}</div>)}{Array.from({length:base.getDay()},(_,i)=><div key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`,count=inMonth.filter(e=>dateKey(e.starts_at)===date).length;return <button key={date} aria-pressed={day===date} aria-label={`${date}, ${count} events`} className={`min-h-16 border-t p-2 text-center text-sm sm:min-h-20 ${day===date?"bg-accent":"hover:bg-muted"}`} onClick={()=>{setDay(day===date?null:date);}}>{i+1}{count>0&&<span className="mx-auto mt-1 block h-1.5 w-1.5 rounded-full bg-primary"/>}</button>;})}</div>
 {day&&<Button variant="ghost" onClick={()=>setDay(null)}>Show whole month</Button>}
 <section className="space-y-3" aria-label="Event agenda">{visible.length===0&&<p className="rounded-xl border p-6 text-muted-foreground">No events scheduled {day?"on this day":"this month"}.</p>}{visible.map(e=><article className="rounded-xl border bg-card p-5" key={e.id}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{e.title}</h3><p className="mt-1 text-sm">{format(e.starts_at)} – {format(e.ends_at)}</p><p className="mt-1 text-sm text-muted-foreground">{e.student_id?people.find(p=>p.id===e.student_id)?.full_name??"Student":"Whole studio"}{e.location&&` · ${e.location}`}</p><p className="mt-2 whitespace-pre-wrap text-sm">{e.description}</p></div>{teacher&&e.teacher_id===userId&&<Button variant="outline" onClick={()=>setEditing(e)}>Edit event</Button>}</div></article>)}</section>
 {editing!==undefined&&<section className="rounded-xl border bg-card p-6" aria-label="Event editor"><div className="mb-4 flex justify-between"><h2 className="font-semibold">{editing?"Edit event":"New event"}</h2><Button variant="ghost" onClick={()=>setEditing(undefined)}>Close</Button></div><EventEditor key={editing?.id??"new"} event={editing} people={people}/>{editing&&<details className="mt-5"><summary className="cursor-pointer text-sm text-destructive">Delete event</summary><p className="my-3 text-sm">This removes the event from everyone’s calendar.</p><ActionForm action={deleteEvent} label="Confirm deletion"><input type="hidden" name="id" value={editing.id}/></ActionForm></details>}</section>}
 </div>;
}
function EventEditor({event,people}:{event:CalendarEvent|null;people:{id:string;full_name:string;membershipRole:string}[]}){
 const [start,setStart]=useState(event?localValue(event.starts_at):""),[end,setEnd]=useState(event?localValue(event.ends_at):"");
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 return <ActionForm action={saveEvent} label="Save event"><input type="hidden" name="id" value={event?.id??""}/><input type="hidden" name="starts_at" value={start&&!isNaN(Date.parse(start))?new Date(start).toISOString():""}/><input type="hidden" name="ends_at" value={end&&!isNaN(Date.parse(end))?new Date(end).toISOString():""}/><input type="hidden" name="time_zone" value={zone}/>
 <label className="block text-sm">Title<Input name="title" required maxLength={120} defaultValue={event?.title}/></label><label className="block text-sm">Attendee<select className={field} name="student_id" defaultValue={event?.student_id??""}><option value="">Whole studio</option>{people.filter(p=>p.membershipRole==="student").map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Starts<Input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-sm">Ends<Input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label></div><p className="text-xs text-muted-foreground">Time zone: {zone}. Students see times in their own device time zone.</p><label className="block text-sm">Location<Input name="location" maxLength={300} defaultValue={event?.location}/></label><label className="block text-sm">Notes<textarea className={field} name="description" maxLength={4000} defaultValue={event?.description}/></label></ActionForm>;
}
