"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { changeSharing,removeMaterial,addCloudMaterial,disconnectCloud } from "@/app/(app)/materials/actions";
import type { Material } from "@/lib/database.types";
import { Button } from "@/components/ui/button";
type CloudFile={id:string;name:string};
export function MaterialsWorkspace({userId,studioId,materials,providers}:{userId:string;studioId:string;materials:Material[];providers:{id:string;name:string;ready:boolean;connected:boolean}[]}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[files,setFiles]=useState<CloudFile[]>([]),[selected,setSelected]=useState("");const router=useRouter();
 async function run(fn:()=>Promise<{error?:string}>,success:string){setBusy(true);setError("");setMessage("");try{const r=await fn();if(r.error)setError(r.error);else{setMessage(success);router.refresh();}}catch{setError("That didn't work. Please try again.");}finally{setBusy(false);}}
 async function upload(file:File){await run(async()=>{if(file.size>20*1024*1024||!file.size)return {error:"Choose a file up to 20 MB."};const db=createClient();const path=`${userId}/${crypto.randomUUID()}`;const {error}=await db.storage.from("materials").upload(path,file,{contentType:file.type||"application/octet-stream"});if(error)return {error:"Upload failed. Please try again."};const saved=await db.from("materials").insert({studio_id:studioId,owner_id:userId,name:file.name.slice(0,255),storage_path:path,mime_type:file.type||"application/octet-stream",size_bytes:file.size});if(saved.error){await db.storage.from("materials").remove([path]);return {error:"Couldn't save this material."};}return {};},"File uploaded privately.");}
 async function browse(provider:string){setSelected(provider);await run(async()=>{const r=await fetch(`/api/cloud/${provider}/files`),data=await r.json();setFiles(data.files??[]);return {error:data.error};},"Files loaded.");}
 return <div className="space-y-6">
 <section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Upload a material</h2><p className="my-2 text-sm text-muted-foreground">Store a file securely in StudioFlow. Up to 20 MB. Files start private.</p><input type="file" aria-label="Upload material" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value="";}}/></section>
 <section><h2 className="mb-3 font-semibold">Cloud accounts</h2><div className="grid gap-3 lg:grid-cols-3">{providers.map(p=><div className="space-y-3 rounded-xl border bg-card p-4" key={p.id}><h3 className="font-medium">{p.name}</h3><p className="text-sm text-muted-foreground">{p.connected?"Connected":p.ready?"Not connected":"Administrator setup required"}</p>{p.ready?<a className="inline-block text-sm underline" href={`/api/cloud/${p.id}/connect`}>{p.connected?"Reconnect":"Connect account"}</a>:<p className="text-xs text-muted-foreground">This connection will become available once StudioFlow’s app credentials are configured.</p>}{p.connected&&<><Button variant="outline" disabled={busy} onClick={()=>browse(p.id)}>Browse files</Button><label className="block text-sm">Store a file in {p.name}<input type="file" className="mt-2 block w-full text-xs" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{if(file.size>3*1024*1024)return {error:"Cloud uploads support files up to 3 MB. Use the provider's app for larger files."};const body=new FormData();body.set("file",file);const res=await fetch(`/api/cloud/${p.id}/files`,{method:"POST",body});const data=await res.json();if(data.error)return {error:data.error};return await addCloudMaterial(p.id,data.file.id);},"File stored in your cloud account and added privately.");e.target.value="";}}/></label><details><summary className="cursor-pointer text-xs">Disconnect</summary><p className="my-2 text-xs">Removes this connection and its shared materials from StudioFlow. Original cloud files stay in your drive. Revoke StudioFlow access in your provider account to revoke its authorization.</p><Button variant="outline" disabled={busy} onClick={()=>run(()=>disconnectCloud(p.id),"Account disconnected.")}>Confirm disconnect</Button></details></>}</div>)}</div></section>
 {selected&&<section className="rounded-xl border p-4"><div className="flex justify-between"><h2 className="font-medium">Choose a cloud file</h2><Button variant="ghost" onClick={()=>{setSelected("");setFiles([]);}}>Close</Button></div><p className="my-2 text-xs text-muted-foreground">Up to 100 files: root files for OneDrive and Dropbox; files created through StudioFlow for Google Drive. Add a file, then choose Share with studio.</p>{files.length===0&&<p className="text-sm">No files found.</p>}{files.map(f=><div key={f.id} className="flex items-center justify-between gap-3 border-t py-2"><span className="break-all text-sm">{f.name}</span><Button variant="outline" disabled={busy} onClick={()=>run(()=>addCloudMaterial(selected,f.id),"Material added privately.")}>Add</Button></div>)}</section>}
 <p role="status" className="text-sm">{busy?"Working…":message}</p>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 <section className="space-y-3"><h2 className="font-semibold">Your studio materials</h2>{materials.length===0&&<p className="rounded-xl border p-6 text-muted-foreground">No files yet. Upload a material to get started.</p>}{materials.map(m=><article className="rounded-xl border bg-card p-4" key={m.id}><div className="flex flex-wrap justify-between gap-3"><div><a className="break-all text-sm font-medium underline" href={`/api/materials/${m.id}/download`}>{m.name}</a><p className="mt-1 text-xs text-muted-foreground">{m.shared?"Shared with studio":"Private"} · {m.connection_id?"Cloud file":"StudioFlow storage"} · {(m.size_bytes/1024).toFixed(0)} KB</p></div>{m.owner_id===userId&&<div className="flex flex-wrap gap-2"><Button disabled={busy} variant="outline" onClick={()=>run(()=>changeSharing(m.id,!m.shared),m.shared?"Material is now private.":"Shared with your studio.")}>{m.shared?"Make private":"Share with studio"}</Button><details><summary className="cursor-pointer p-2 text-sm">Remove</summary><p className="my-2 max-w-xs text-xs">Remove this material from StudioFlow? Cloud originals are kept; StudioFlow uploads are deleted.</p><Button disabled={busy} variant="outline" onClick={()=>run(()=>removeMaterial(m.id),"Material removed.")}>Confirm removal</Button></details></div>}</div></article>)}</section>
 </div>;
}
